
version: '3'

services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://db_test_wb53_user:E0IJfLJaXOXR86Wx0X6ZCBmhsNLD8HQB@dpg-crn8mb08fa8c738bb4gg-a.oregon-postgres.render.com/db_test_wb53

  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management  
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://db_test_wb53_user:E0IJfLJaXOXR86Wx0X6ZCBmhsNLD8HQB@dpg-crn8mb08fa8c738bb4gg-a.oregon-postgres.render.com/db_test_wb53