name: Deploy book_catalog

on:
  push: 
    branches:
      - master
    paths:
      - book_catalog/**

  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      NAME: book_catalog
      DIRECTORY: book_catalog

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR details and set environment variables
        run: |
          ACR_NAME=$(az acr list --query "[0].name" -o tsv)
          echo "CONTAINER_REGISTRY=${ACR_NAME}.azurecr.io" >> $GITHUB_ENV
          echo "REGISTRY_UN=${ACR_NAME}" >> $GITHUB_ENV
          REGISTRY_PW=$(az acr credential show -n ${ACR_NAME} --query "passwords[0].value" -o tsv)
          echo "REGISTRY_PW=${REGISTRY_PW}" >> $GITHUB_ENV

      - name: Set permissions for scripts
        run: |
          chmod +x ./scripts/build-image.sh
          chmod +x ./scripts/push-image.sh
          chmod +x ./scripts/deploy.sh

      - name: Build Docker image
        run: ./scripts/build-image.sh

      - name: Publish Docker image
        run: ./scripts/push-image.sh

      - name: Get AKS credentials
        run: |
          AKS_NAME=$(az aks list --query "[0].name" -o tsv)
          az aks get-credentials --name $AKS_NAME --resource-group $(az aks list --query "[0].resourceGroup" -o tsv)

      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh  
        