name: Deploy book_catalog

on:
  push: 
    branches:
      - master
    paths:
      - book_catalog/**
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ env.REGISTRY_UN }}
      REGISTRY_PW: ${{ env.REGISTRY_PW }}
      NAME: book_catalog
      DIRECTORY: book_catalog
      KUBE_CONFIG: ${{ env.KUBE_CONFIG }}  # Use the variable directly

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set executable permissions for all necessary scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x ./scripts/build-image.sh
          chmod +x ./scripts/push-image.sh
          chmod +x ./scripts/deploy.sh

      # Build the Docker image
      - name: Build Docker image
        run: ./scripts/build-image.sh

      # Push the Docker image to the container registry
      - name: Publish Docker image
        run: ./scripts/push-image.sh

      # Install Kubectl and configure it with the cluster
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}  # Use the variable directly
          kubectl-version: v1.24.2

      # Deploy the microservice to Kubernetes
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh 