name: Security Check

on:
  # Trigger the workflow on push to the master branch or changes to book_catalog directory
  push: 
    branches:
      - master
    paths:
      - book_catalog/**

  # Allows the workflow to be triggered manually
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: book_catalog:latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Run Bandit to check Python code security issues
      - name: Run Bandit security check
        run: |
          pip install bandit
          bandit -r ./book_catalog

      # Install Docker to allow building and scanning images
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} ./book_catalog

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.42.0/trivy_0.42.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.42.0_Linux-64bit.deb

      # Scan Docker image for vulnerabilities using Trivy
      - name: Run Trivy vulnerability scan on Docker image
        run: trivy image --severity HIGH,CRITICAL ${{ env.IMAGE_NAME }}