name: Deploy microservice

on:

  push:
    branches:
      - master

  workflow_dispatch: 

jobs:
  
  deploy:
    runs-on: ubuntu-latest 
    env:
      VERSION: ${{ github.sha }}
      TF_VERSION: '1.0.0'  # Specify Terraform version

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          pip install -r book_catalog/app/requirements.txt

      - name: Run Bandit security check
        run: |
          pip install bandit
          bandit -r book_catalog/app -o bandit_report.json -f json || exit 1

      - name: Install Safety
        run: |
          pip install safety

      # Upload the Bandit security report as an artifact
      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.json
