name: Deploy microservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      TF_VERSION: '1.0.0'  # Specify Terraform version

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          pip install -r book_catalog/app/requirements.txt

      # Run Bandit security check and generate report
      - name: Run Bandit security check
        run: |
          pip install bandit
          bandit -r book_catalog/app -o bandit_report.json -f json || echo "Bandit found issues"

      # Upload Bandit report as an artifact
      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.json

      # Install Safety and run the security check on dependencies
      - name: Run Safety vulnerability check
        run: |
          pip install safety
          safety check -r book_catalog/app/requirements.txt --ignore <vulnerability_id> --output json > safety_report.json || echo "Safety found issues"

      # Upload Safety report as an artifact
      - name: Upload Safety report
        uses: actions/upload-artifact@v3
        with:
          name: safety-report
          path: safety_report.json

      # Fail the job if vulnerabilities are found in Bandit
      - name: Check for vulnerabilities in Bandit
        run: |
          if grep -q '"issue_severity":' bandit_report.json; then
            cat bandit_report.json
            echo "Bandit found vulnerabilities, failing the build."
            exit 1
          fi

      # Fail the job if vulnerabilities are found in Safety
      - name: Check for vulnerabilities in Safety
        run: |
          if grep -q '"vulnerabilities":' safety_report.json; then
            cat safety_report.json
            echo "Safety found vulnerabilities, failing the build."
            exit 1
          fi
