name: Deploy microservice

on:

  push:
    branches:
      - master

  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest 
    env:
      VERSION: ${{ github.sha }}
      TF_VERSION: '1.0.0'  # Specify Terraform version

    steps:
      - uses: actions/checkout@v3

      # Automated Security Checks
      - name: Run Safety check
        run: |
          pip install safety
          safety check -r requirements.txt

      - name: Run Bandit security check
        run: |
          pip install bandit
          bandit -r .