name: Deploy Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - scripts/terraform/**

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription
        run: az account set --subscription $(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r '.subscriptionId')

      - name: Terraform Init
        run: terraform init
        working-directory: scripts/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: scripts/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: scripts/terraform