name: Deploy Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - scripts/terraform/**
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: scripts/terraform

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="subscription_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" \
            -var="client_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)" \
            -var="client_secret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" \
            -var="tenant_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)" \
            -var="kubernetes_version=1.30.3"
        working-directory: scripts/terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="subscription_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" \
            -var="client_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)" \
            -var="client_secret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" \
            -var="tenant_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)" \
            -var="kubernetes_version=1.30.3"
        working-directory: scripts/terraform

      - name: Verify Terraform State
        run: terraform show
        working-directory: scripts/terraform

      - name: Get AKS Credentials
        run: |
          RESOURCE_GROUP=$(terraform output -json resource_group_name | jq -r '.')
          AKS_NAME=$(terraform output -json aks_cluster_name | jq -r '.')
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_NAME --overwrite-existing
          kubectl config view --raw > kubeconfig
          echo "KUBE_CONFIG=$(base64 -w 0 kubeconfig)" >> $GITHUB_ENV
        working-directory: scripts/terraform

      - name: Fetch Terraform Outputs
        id: fetch_outputs
        run: |
          echo "CONTAINER_REGISTRY=$(terraform output -json container_registry | jq -r '.')" >> $GITHUB_ENV
          echo "REGISTRY_UN=$(terraform output -json registry_username | jq -r '.')" >> $GITHUB_ENV
          echo "REGISTRY_PW=$(terraform output -json registry_password | jq -r '.')" >> $GITHUB_ENV
          echo "KUBE_CONFIG=$(terraform output -json kubeconfig | jq -r '.')" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=$(terraform output -json resource_group_name | jq -r '.')" >> $GITHUB_ENV
          echo "AKS_NAME=$(terraform output -json aks_cluster_name | jq -r '.')" >> $GITHUB_ENV
        working-directory: scripts/terraform

      - name: Debug Outputs
        run: |
          echo "Resource Group: ${{ env.RESOURCE_GROUP }}"
          echo "AKS Cluster Name: ${{ env.AKS_NAME }}"
          echo "Container Registry: ${{ env.CONTAINER_REGISTRY }}"
          echo "Registry Username: ${{ env.REGISTRY_UN }}"
          echo "Kubeconfig is set: ${{ env.KUBE_CONFIG != '' }}"